core-identity-uri: ${SERVICE_SCHEME}://${CORE_IDENTITY_HOST}:${CORE_IDENTITY_PORT}

server:
  port: ${SERVER_PORT:8080}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_SERVER}/oauth2/jwks
          issuer-uri: ${AUTH_SERVER}
  ai:
    mcp:
      client:
        enabled: true
        name: mcp-client
        version: 1.0.0
        request-timeout: ${MCP_REQUEST_TIMEOUT}
        type: SYNC
        sse:
          connections:
            server1:
              url: ${MCP_SERVER}
    openai:
      api-key: ${OPEN_AI_API_KEY}
      base-url: ${OPEN_AI_BASE_URL}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

springdoc:
  api-docs:
    enabled: true
    path: /api/ai/v3/api-docs
  swagger-ui:
    enabled: true
    path: /api/ai/swagger-ui.html

management:
  tracing:
    enabled : true
    sampling:
      probability: 1.0
  endpoints:
    web:
      base-path: ""
      path-mapping:
        health: health
  health:
    ldap:
      enabled: false

thread:
  pool:
    core-size: 5
    max-size: 20
    queue-capacity: 100